### ISSUE TITLE
erreur durant la mise à jour des conversation

### ISSUE THREAD

**Issue by yapudjus** [romainflcht/igdm_terminal#1]
bonjour, je viens d'installer ce projet car la version web d'instagram n'est pas simple à naviguer au clavier, cependant j'obptiens cette erreur:
```Traceback (most recent call last):
  File "/home/yapudjus/Documents/code/igdm_terminal/main.py", line 30, in <module>
    inbox.update_indox(CONV_INBOX_NB)
  File "/home/yapudjus/Documents/code/igdm_terminal/inbox.py", line 49, in update_indox
    format_last_item(self._session, thread['items'][0]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yapudjus/Documents/code/igdm_terminal/format_data.py", line 131, in format_last_item
    user = fetch_username_by_id(session, item.get('user_id')) + ' à '
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yapudjus/Documents/code/igdm_terminal/fetch_data.py", line 20, in fetch_username_by_id
    data = json.load(save_file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
je suis dans un virtualenv python avec cette configuration

 ```(venv) ┌─[yapudjus@thickpad] - [~/Documents/code/igdm_terminal] - [5440]
└─[$] pip list                                                                                                                                              [15:55:43]
Package            Version
------------------ --------
certifi            2023.5.7
charset-normalizer 3.1.0
idna               3.4
markdown-it-py     3.0.0
mdurl              0.1.2
Pillow             9.5.0
pip                22.3.1
Pygments           2.15.1
requests           2.31.0
rich               13.4.2
setuptools         65.5.0
urllib3            2.0.3

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
(venv) ┌─[yapudjus@thickpad] - [~/Documents/code/igdm_terminal] - [5441]
└─[$] python -V                                                                                                                                             [15:55:50]
Python 3.11.3
(venv) ┌─[yapudjus@thickpad] - [~/Documents/code/igdm_terminal] - [5442]
└─[$] neofetch                                                                                                                                              [15:55:54]
                   -`                    yapudjus@thickpad 
                  .o+`                   ----------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: 20JRS13E00 ThinkPad L570 W10DG 
               `+oooooo:                 Kernel: 6.4.11-arch2-1 
               -+oooooo+:                Uptime: 2 hours, 34 mins 
             `/:-:++oooo+:               Packages: 2108 (pacman), 21 (flatpak) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 1366x768 
          `/+++ooooooooooooo/`           DE: Plasma 5.27.7 
         ./ooosssso++osssssso+`          WM: kwin 
        .oossssso-````/ossssss+`         WM Theme: Aritim-Dark 
       -osssssso.      :ssssssso.        Theme: [Plasma], Breeze [GTK2/3] 
      :osssssss/        osssso+++.       Icons: OieIcons [Plasma], OieIcons [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: konsole 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i3-6100U (4) @ 2.300GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel Skylake GT2 [HD Graphics 520] 
 `++:.                           `-/+/   Memory: 3718MiB / 15888MiB 
 .`                                 `/
                                                                 
                                                                 
```
la connexion à mon compte instagram est fonctionelle

**Comment by romainflcht** [comment]
Merci beaucoup pour le fix !
